Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,8 +1,11 @@
 # The name of our workflow
-name: Build
+name: Build with XOR Patch
 permissions:
   contents: read
-on: [push, pull_request]
+on: 
+  push:
+  pull_request:
+  workflow_dispatch: # 允许网页手动点击运行
 
 jobs:
   build:
@@ -15,22 +18,34 @@ jobs:
     steps:
       - name: Use debug signing
         run: mkdir -p ~/.gradle && echo -e "icsopenvpnDebugSign=true\norg.gradle.jvmargs=-Xmx2048M" > ~/.gradle/gradle.properties
+      
       - name: Checkout the code
         uses: actions/checkout@v4
         with:
           submodules: true
+          
+      - name: Copy and Apply XOR patches
+        run: |
+          cp -r tunnelblick-patches/* main/src/main/cpp/openvpn/
+          cd main/src/main/cpp/openvpn
+          patch -p1 --forward < 02-tunnelblick-openvpn_xorpatch-a.diff || echo "Patch A failed"
+          patch -p1 --forward < 03-tunnelblick-openvpn_xorpatch-b.diff || echo "Patch B failed"
+          patch -p1 --forward < 04-tunnelblick-openvpn_xorpatch-c.diff || echo "Patch C failed"
+          patch -p1 --forward < 05-tunnelblick-openvpn_xorpatch-d.diff || echo "Patch D failed"
+          patch -p1 --forward < 06-tunnelblick-openvpn_xorpatch-e.diff || echo "Patch E failed"
+
       - name: set up JDK 17
         uses: actions/setup-java@v4
         with:
           distribution: 'zulu'
           java-version: 17
           cache: 'gradle'
+          
       - name: Setup Android SDK
         uses: android-actions/setup-android@v3
+        
       - name: Build the app
         run: ./gradlew assemble${{ matrix.target }}Release
-      - name: Run Unit tests
-        run: ./gradlew test${{ matrix.target }}ReleaseUnitTest
 
       - name: Archive apk artifact
         uses: actions/upload-artifact@v4
